#!/bin/sh
. /etc/profile >/dev/null 2>&1

start=$(find ${SDCARD}/log/startup.log -mmin -10|wc -l)
if [ $start -gt 0 ]
then
  echo "tro baldaŭ post rekomencado."
  exit
fi

if touch ${SDCARD}/test.$$ ; then
 echo carte OK
 rm -f ${SDCARD}/test.$$
else
 echo fsck à faire
 fsck.vfat -y /dev/mmcblk0p1
 reboot
fi

for SERVICE in lighttpd rtsp
do 
  if  ! service $SERVICE status
  then
    echo "$SERVICE-statuso erare, ni rekomencas ĝin."
    service $SERVICE start
  fi
done
