#!/bin/sh
. /etc/profile >/dev/null 2>&1

start=$(find ${SDCARD}/log/startup.log -mmin -10|wc -l)
if [ $start -gt 0 ]
then
  echo "tro baldaŭ post rekomencado."
  exit
fi

for SERVICE in lighttpd rtsp
do 
  if  ! service $SERVICE status
  then
    echo "$SERVICE-statuso erare, ni rekomencas ĝin."
    service $SERVICE start
  fi
done
