#!/bin/bash

BAZO=$(dirname $(readlink -f $0))
cd "$BAZO"

for FIC in index
do
  
  if [ ../www/$FIC.html -nt pot/$FIC.pot ] ; then
    lib/html2pot ../www/$FIC.html >pot/$FIC.pot
  fi
  
  for lang in ar bn de en es fr hi it ja ms nl pa po pt ru zh
  do
    if [ ! -f pot/$FIC.$lang.po ] ; then
      echo "krei pot/${FIC}.${lang}.po"
      cat pot/${FIC}.pot|sed "s/^\"Language: .*\\\n\"/\"Language: "${lang}"\\\n\"/" > pot/${FIC}.${lang}.po
      lib/traduki_po.sh pot/${FIC}.${lang}.po
      mv pot/${FIC}.${lang}.po.nova pot/${FIC}.${lang}.po
    elif [ pot/$FIC.pot -nt pot/${FIC}.${lang}.po ]; then
      echo "kunfandi pot/${FIC}.${lang}.po"
      msgmerge pot/${FIC}.${lang}.po pot/$FIC.pot
      lib/traduki_po.sh pot/${FIC}.${lang}.po
      mv pot/${FIC}.${lang}.po.nova pot/${FIC}.${lang}.po
    else
      lib/traduki_po.sh pot/${FIC}.${lang}.po
      if ! diff pot/${FIC}.${lang}.po.nova pot/${FIC}.${lang}.po >/dev/null 2>&1 ; then
        echo "ĝisdatigi pot/${FIC}.${lang}.po"
        mv pot/${FIC}.${lang}.po.nova pot/${FIC}.${lang}.po
      else
        rm pot/${FIC}.${lang}.po.nova
      fi
    fi
    if [ ! -f ../www/js/${FIC}.${lang}.json ] ; then
      echo krei www/js/${FIC}.${lang}.json
      lib/po2json pot/${FIC}.${lang}.po ../www/js/${FIC}.${lang}.json
    elif [ pot/${FIC}.${lang}.po -nt ../www/js/${FIC}.${lang}.json ] ; then
      echo ĝisdatigi www/js/${FIC}.${lang}.json
      lib/po2json pot/${FIC}.${lang}.po ../www/js/${FIC}.${lang}.json
    fi
  done
done  
