#!/bin/sh
. /etc/profile >/dev/null 2>&1

#### KOMENCO DE MASTRUMA KAPLINIO
# Mallonga-priskribo: 
# Komenco:
# Retejo-administrita:ne
#### FINO DE MASTRUMA KAPLINIO

SERVICE_NAME=""
BIN=""
OPTS=""

PIDFILE="/var/run/${SERVICE_NAME}.pid"
LOGDIR="${SDCARD}/log"
LOGPATH="$LOGDIR/${SERVICE_NAME}.log"
CONFIG="${SDCARD}/config/${SERVICE_NAME}.conf"


status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A ${SERVICE_NAME} is already running, please stop it or reboot"
  else
    echo "Starting ${SERVICE_NAME}"
    echo "================== START ===============" >> "$LOGPATH"
    echo "${BIN} ${OPTS}" >> "$LOGPATH"
    ${BIN} ${OPTS} 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"                                                   
  if [ "$pid" ]; then                                                                   
    kill "$pid"                                                         
    provo=0
    while [ -d /proc/"$pid" -a $provo -lt 30 ]                                           
    do                                                                  
     provo=$(($provo+1))
     sleep 1                                                         
    done                                                                
    if [ $provo -ge 30 ]
    then
     kill -9 "$pid"                                                         
     echo "Procezo $pid ne ĉesis !"
    fi                                                                    
  fi                                                                    
  rm "$PIDFILE" 1> /dev/null 2>&1                                       
}

restart()
{
  stop
  start
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status|restart)
    $1
    ;;
  esac
fi
