#!/bin/sh
. /etc/profile >/dev/null
export LD_LIBRARY_PATH="${SDCARD}/lib:/thirdlib:/system/lib/:/ipc/lib/"

#### KOMENCO DE MASTRUMA KAPLINIO
# Mallonga-priskribo: pozicionas motoro al P0
# Komenco: 00
# Retejo-administrita: ne
#### FINO DE MASTRUMA KAPLINIO

SERVICE_NAME=""
BIN=""
OPTS=""

PIDFILE="/var/run/${SERVICE_NAME}.pid"
LOGDIR="${SDCARD}/log"
LOGPATH="$LOGDIR/${SERVICE_NAME}.log"
CONFIG="${SDCARD}/config/${SERVICE_NAME}.conf"


status()
{
cat /tmp/motoraValoro
return 0
}

start()
{
.  JsAlVar ${SDCARD}/www/ipcam/config/ptz.conf ptz_conf 11
  motor -x $P0X -y $P0Y -r $RAPIDECO;
return 0
}

stop()
{
return 0
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
