#!/bin/sh
SERVICE_NAME="network"

status()
{
 eth0_state=`cat /sys/class/net/eth0/operstate`
 wlan0_state=`cat /sys/class/net/wlan0/operstate`
 echo "eth0 " $eth0_state " ; wlan0 " $wlan0_state "."
}

start()
{
 ifconfig eth0 up
 sleep 5
 eth0_state=`cat /sys/class/net/eth0/operstate`

 ## elektu la interfacon por komenci.
 if [ x$eth0_state = xdown ]
 then
  ifconfig wlan0 up
  ifconfig eth0 down
  network_interface_name="wlan0"
  if [ ! -f $CONFIGPATH/wpa_supplicant.conf ]; then
   echo "Averto: Vi devas agordi wpa_supplicant por uzi wifi. Bonvolu vidi /system/sdcard/config/wpa_supplicant.conf.dist ." >> $LOGPATH
  fi
  wpa_supplicant_status="$(wpa_supplicant -d -B -i wlan0 -c $CONFIGPATH/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid)"
  echo "wpa_supplicant: $wpa_supplicant_status" >> $LOGPATH
 else
  network_interface_name="eth0"
 fi

 ## Configure network address
 if [ -f "$CONFIGPATH/staticip.conf" ]; then
  # Install a resolv.conf if present so DNS can work
  if [ -f "$CONFIGPATH/resolv.conf" ]; then
    cp "$CONFIGPATH/resolv.conf" /etc/resolv.conf
  fi

  # Configure staticip/netmask from config/staticip.conf
  staticip_and_netmask=$(cat "$CONFIGPATH/staticip.conf" | grep -v "^$" | grep -v "^#")
  ifconfig "$network_interface_name" $staticip_and_netmask
  ifconfig "$network_interface_name" up
  # Configure default gateway
  if [ -f "$CONFIGPATH/defaultgw.conf" ]; then
    defaultgw=$(cat "$CONFIGPATH/defaultgw.conf" | grep -v "^$" | grep -v "^#")
    route add default gw $defaultgw $network_interface_name
    echo "Configured $defaultgw as default gateway" >> $LOGPATH
  fi
  echo "Configured $network_interface_name with static address $staticip_and_netmask" >> $LOGPATH
 else
  # Configure with DHCP client
  ifconfig "$network_interface_name" up
  udhcpc_status=$(udhcpc -i "$network_interface_name" -p /var/run/udhcpc.pid -b -x hostname:"$(hostname)")
  echo "udhcpc: $udhcpc_status" >> $LOGPATH
 fi
}


if [ $# -eq 0 ]; then
  start
else
  case $1 in start|status)
    $1
    ;;
  esac
fi
