#!/bin/sh
SERVICE_NAME="RTSP MJPEG Server"
PIDFILE="/var/run/rtsp_server.pid"
LOGDIR="/opt/media/sdc/log"
LOGPATH="$LOGDIR/rtsp_server.log"
export LD_LIBRARY_PATH='/opt/media/sdc/lib:/thirdlib:/system/lib/:/ipc/lib/'

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A rtsp_server is already running, please stop it or reboot"
  else
    echo "Starting rtsp_server"
    /opt/media/sdc/controlscripts/rtsp-h264 stop

    echo "================== START ===============" >> "$LOGPATH"
    echo "/opt/media/sdc/bin/rtsp_server -W 1280 -H 720 -j 60 -Q 5 -u media/stream1 -P 554" >> "$LOGPATH"
    /opt/media/sdc/bin/rtsp_server -W 1280 -H 720 -j 60 -Q 5 -u media/stream1 -P 554 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid"
    rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
