#!/bin/sh
. /etc/profile >/dev/null
SERVICE_NAME="RTSP Server"
PIDFILE="/var/run/rtsp_server.pid"
LOGDIR="${SDCARD}/log"
LOGPATH="$LOGDIR/rtsp_server.log"
export LD_LIBRARY_PATH="${SDCARD}/lib:/thirdlib:/system/lib/:/ipc/lib/"

CONFPATH=${SDCARD}/www/ipcam/config

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A rtsp_server is already running, please stop it or reboot"
  else
    echo "Starting rtsp_server"

    echo "================== START ===============" >> "$LOGPATH"
    echo "${SDCARD}/bin/rtsp_server ${CONFPATH}" >> "$LOGPATH"
    ${SDCARD}/bin/rtsp_server ${CONFPATH} 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid"
    rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
