#!/bin/sh
. /etc/profile >/dev/null 2>&1

#### KOMENCO DE MASTRUMA KAPLINIO
# Mallonga-priskribo: telnet servilo. Uzu ssh anstataŭe.
# Komenco: 20
# Retejo-administrita: ies
#### FINO DE MASTRUMA KAPLINIO

SERVICE_NAME="Telnet Server"
PIDFILE="/var/run/telnet-server.pid"
export LD_LIBRARY_PATH='${SDCARD}/lib/:/thirdlib:/system/lib/:/ipc/lib/'
PATH=${SDCARD}/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin

if [ ! -f ${SDCARD}/config/telnetd.conf ]; then
  cp ${SDCARD}/config/telnetd.conf.dist ${SDCARD}/config/telnetd.conf
fi

if [ -f ${SDCARD}/config/telnetd.conf ]; then
  . ${SDCARD}/config/telnetd.conf
fi


status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A telnet server is already running, please stop it or reboot"
  else
    telnetd -p$TELNET_PORT
    sleep 1
    PID=$(ps | grep "[t]elnetd -p$TELNET_PORT" | awk '{print $1}')
    echo "$PID" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"                                                   
  if [ "$pid" ]; then                                                                   
    kill "$pid"                                                         
    provo=0
    while [ -d /proc/"$pid" -a $provo -lt 30 ]                                           
    do                                                                  
     provo=$(($provo+1))
     sleep 1                                                         
    done                                                                
    if [ $provo -ge 30 ]
    then
     kill -9 "$pid"                                                         
     echo "Procezo $pid ne ĉesis !"
    fi                                                                    
  fi                                                                    
  rm "$PIDFILE" 1> /dev/null 2>&1                                       
}

restart()
{
  stop
  start
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status|restart)
    $1
    ;;
  esac
fi
