#!/bin/sh
. /etc/profile >/dev/null 2>&1

#### KOMENCO DE MASTRUMA KAPLINIO
# Mallonga-priskribo: timelapse servilo. Registras bildon regule.
# Komenco: 20
# Retejo-administrita: ne
#### FINO DE MASTRUMA KAPLINIO

SERVICE_NAME="Timelapse"
PIDFILE='/var/run/timelapse.pid'

status()
{  PID=$(cat $PIDFILE)
   if [ "$PID" != "" ]; then
   cat $PIDFILE
   fi
}

start()
{
  LOG=/dev/null
  echo "Starting timelapse"
  ${SDCARD}/bin/busybox nohup ${SDCARD}/scripts/timelapse.sh &> /dev/null &
  PID=$!
  echo $PID > $PIDFILE
  echo $PID
}

stop()
{ 
  PID=$(cat $PIDFILE)
  kill -9 $PID
  rm $PIDFILE
}

restart()
{
  stop
  start
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status|restart)
    $1
    ;;
  esac
fi
