#!/bin/sh                                                                                                                                                      
/opt/media/mmcblk0p1/www/../controlscripts/telnet-server    
