#!/bin/bash

BAZO=$(dirname $(readlink -f $0))
cd "$BAZO"

for FIC in reto.html pantilt.html rtsp.html index.html logs.html cgi-bin/status_overview.cgi
do
  
  if [ ! -f ipcam_pot/$FIC.pot -o ../karto/www/ipcam/$FIC -nt ipcam_pot/$FIC.pot ] ; then
    mkdir -p ipcam_pot/$(dirname $FIC)
    lib/html2pot ../karto/www/ipcam/$FIC >ipcam_pot/$FIC.pot
  fi
  
  mkdir -p ../karto/www/ipcam/lok/$(dirname $FIC)
  for lang in ar bn de en es fr hi it ja ms nl pa pl pt ru zh
  do
    if [ ! -f ipcam_pot/$FIC.$lang.po ] ; then
      echo "krei ipcam_pot/${FIC}.${lang}.po"
      cat ipcam_pot/${FIC}.pot|sed "s/^\"Language: .*\\\n\"/\"Language: "${lang}"\\\n\"/" > ipcam_pot/${FIC}.${lang}.po
      lib/traduki_po.sh ipcam_pot/${FIC}.${lang}.po
      mv ipcam_pot/${FIC}.${lang}.po.nova ipcam_pot/${FIC}.${lang}.po
    elif [ ipcam_pot/$FIC.pot -nt ipcam_pot/${FIC}.${lang}.po ]; then
      echo "kunfandi ipcam_pot/${FIC}.${lang}.po"
      msgmerge -U ipcam_pot/${FIC}.${lang}.po ipcam_pot/$FIC.pot
      lib/traduki_po.sh ipcam_pot/${FIC}.${lang}.po
      mv ipcam_pot/${FIC}.${lang}.po.nova ipcam_pot/${FIC}.${lang}.po
    else
      lib/traduki_po.sh ipcam_pot/${FIC}.${lang}.po
      if ! diff ipcam_pot/${FIC}.${lang}.po.nova ipcam_pot/${FIC}.${lang}.po >/dev/null 2>&1 ; then
        echo "ĝisdatigi ipcam_pot/${FIC}.${lang}.po"
        mv ipcam_pot/${FIC}.${lang}.po.nova ipcam_pot/${FIC}.${lang}.po
      else
        rm ipcam_pot/${FIC}.${lang}.po.nova
      fi
    fi
    if [ ! -f ../karto/www/ipcam/lok/${FIC}.${lang}.json ] ; then
      echo krei karto/www/ipcam/lok/${FIC}.${lang}.json
      lib/po2json ipcam_pot/${FIC}.${lang}.po ../karto/www/ipcam/lok/${FIC}.${lang}.json
    elif [ ipcam_pot/${FIC}.${lang}.po -nt ../karto/www/ipcam/lok/${FIC}.${lang}.json ] ; then
      echo ĝisdatigi karto/www/ipcam/lok/${FIC}.${lang}.json
      lib/po2json ipcam_pot/${FIC}.${lang}.po ../karto/www/ipcam/lok/${FIC}.${lang}.json
    fi
  done
done  
